### ISSUE TITLE
building mpv statically

### ISSUE THREAD

**Issue by hovercats** [hovercats/kiss-somethingsomethingstatic#13]
As per 0.34.0 release, we're stuck with the python based waf build system.
With this buildsystem, we can pass `-enable-static-build`, and to your suprise,
not have a completely static build. itll still link to `libc.so`.
This is not enough. We want libc to be statically linked into mpv aswell.
Also; passing CFLAGS/LDFLAGS=-static like we usually do, does nothing, if not 
make the build fail after configuring.

Also also; as per Nov. 14, 2021, support for the meson buildsystem were added, which
brings some new possibilites. 
By using meson, and a few seds into `build/build.ninja`, I was able to build a
static mpv binary. Albeit, with no sound.

To get sound working again with meson system, I had to not link it statically,
aswell as build alsa-libs' shared libs.
Without these shared libs, I cant get any sound regardless of using waf or meson.
It does however not matter if alsa-libs' `aserver` bin is built statically or
not. 

When using meson, I havent been able to build the manpage either, which Im sure
some may appreciate if where there. 
We could just bundle a premade one instead, and save everyone the time it
takes to compile the manpage aswell, with both buildsystems.

I will have to investigate this further, and Ill probably update this post
with my findings if neccessary.

**Comment by eli-schwartz** [comment]
> When using meson, I havent been able to build the manpage either

This doesn't seem like a meson problem, as you explicitly deleted the parts of your previous build recipe that downloaded and set up a local copy of python-docutils to to get access to the `rst2man` program. (Like meson itself, this should just be a make dependency...)

**Comment by hovercats** [comment]
> > When using meson, I havent been able to build the manpage either
> 
> This doesn't seem like a meson problem, as you explicitly deleted the parts of your previous build recipe that downloaded and set up a local copy of python-docutils to to get access to the `rst2man` program. (Like meson itself, this should just be a make dependency...)

I belive youre right. At the time of creating this issue, I dont recall me getting the manpage to build at all with meson, and I havent really looked into it passed that. Hence me just bundling it instead, as I focused on pirmarly getting mpv to build statically instead. 

Ill take a look at this again, so we can generate the manpage like we used to, instead of just bundling it like we currently do.
Thanks for pointing it out!
